### ISSUE TITLE
arghh - vi har en rød test!

### ISSUE THREAD

**Issue by wdiechmann** [SL2022/ticket#7]
@JacobArrow - er du frisk på at se, hvad der er galt?

😆

**Comment by wdiechmann** [comment]
og husk nu - i sådan en situation - hvor det er en 'anden' der har fjoget - så blam'er man i commit'en istedet for at begynde at fix'e det selv (i hvertfald i første omgang, og helt bestemt i vores repo) 😄

**Comment by JacobArrow** [comment]
Skal jeg for god ordens skyld lave en PR med rettelse af fejlen?

**Comment by wdiechmann** [comment]
@JacobArrow jah - synes du ikke - bare sådan for at øve arbejdsgangen - og check gerne med README - at jeg ikke har glemt noget , eller at det måske står krøllet eller direkte forkert

**Comment by wdiechmann** [comment]
Og bagefter skal jeg høre om du er kommet igennem hele den smøre jeg sendte dig i går?

Og sikkert en liste med spørgsmål, som jeg skal have svaret - eller er det krystalklart?

**Comment by JacobArrow** [comment]
> Og bagefter skal jeg høre om du er kommet igennem hele den smøre jeg sendte dig i går?

Skimmede mig igennem https://hexdocs.pm/phoenix/testing.html, men så fandt "jeg" (mix) jo fejlen og så skulle der jo commit'es ;)

**Comment by wdiechmann** [comment]
@JacobArrow så - nu er Cypress med - og hvis du så ellers også har `npm --prefix=assets install` -ed så skulle du kunne bruge `mix cypress.open`?

**Comment by wdiechmann** [comment]
husk git fetch upstream og git merge ticket/main

**Comment by wdiechmann** [comment]
i din main - naturligvis

**Comment by JacobArrow** [comment]
Hmm
Hvor længe skal den stå og tygge sådan?

user@Jacob-Pc:/mnt/c/Users/Jacob/Elixir/ticket$ mix cypress.open
The database for Ticket.Repo has been dropped
The database for Ticket.Repo has been created

19:19:45.146 [info]  Migrations already up
Starting the phx server...

**Comment by wdiechmann** [comment]
Bange for at det ikke er en *nix ting - checker lige når jeg har spist 😎

Med venlig hilsen
Walther

**Comment by wdiechmann** [comment]
Godmorgen Jacob,

Har du fundet ud af, hvad problemet er?

**Comment by JacobArrow** [comment]
Godmorgen
Nej, jeg googlede lige rundt og fandt umiddelbart ikke noget
Kunne ikke engang finde noget på "mix cypress.open"

**Comment by wdiechmann** [comment]
Hvad med nogen af de links der er i readme?

Med venlig hilsen
Walther

**Comment by JacobArrow** [comment]
Man skulle tro at du godt ved hvad jeg gør forkert, men vil have at jeg selv finder ud af det 😉

**Comment by wdiechmann** [comment]
Ja - det skulle man næsten tro - ikke 😇

En af dagene er jeg pludselig død - og så kan du jo ikke spørge mig 😘

**Comment by wdiechmann** [comment]
Men det er også ok at ‘give fortabt’

Giver du fortabt?


(Hint: cypress - install - linux )

**Comment by JacobArrow** [comment]
NEVER!

Må se om jeg kan få kigget på det i aften

**Comment by wdiechmann** [comment]
That’a’boy :D

**Comment by JacobArrow** [comment]
Så kører bussen igen!
![image](https://user-images.githubusercontent.com/14014012/99720827-9ce71c80-2aae-11eb-9dce-f0135048eeab.png)

**Comment by wdiechmann** [comment]
Så er vi ved at have vores arbejdsbænk på plads 🥰

Nu skal vi så igang med skrivebordsarbejdet 😢
